import sys, re, shutil
sys.stdout.reconfigure(encoding='utf-8')

path = "C:/Users/Windows 10/Desktop/r ta/icdl_study_app.html"
with open(path, encoding='utf-8') as f:
    content = f.read()

additions = {}

# MODULE 0 – Computer Essentials (12→36, +24)
additions['e:"ADSL (Asymmetric Digital Subscriber Line) delivers broadband internet over standard telephone lines. \'Asymmetric\' means download speed is faster than upload."},'] = \
"""      {q:"Which of the following is an OUTPUT device?", o:["Keyboard","Scanner","Microphone","Monitor"], c:3, e:"A monitor displays information from the computer. Keyboards, scanners, and microphones are input devices."},
      {q:"What does GUI stand for?", o:["General User Interface","Graphical User Interface","Global Unified Interface","Guided User Input"], c:1, e:"GUI = Graphical User Interface. Uses windows, icons, menus, and a pointer to make computers easy to use without typing commands."},
      {q:"Which component stores data permanently even after the computer is switched off?", o:["RAM","Cache memory","CPU registers","Hard Disk Drive"], c:3, e:"A Hard Disk Drive (HDD) is non-volatile storage. RAM, cache, and registers are volatile and lose data when power is off."},
      {q:"How many bytes are in one kilobyte (KB)?", o:["100","512","1000","1024"], c:3, e:"1 KB = 1024 bytes. Memory uses powers of 2: 1024 bytes = 1 KB, 1024 KB = 1 MB, 1024 MB = 1 GB."},
      {q:"What type of computer is NOT portable and sits on a desk?", o:["Laptop","Tablet","Desktop","PDA"], c:2, e:"A desktop has separate components (tower, monitor, keyboard, mouse) and is not designed to be portable."},
      {q:"What is the main function of an Operating System?", o:["Browse the internet","Manage hardware and software resources","Create documents","Run antivirus scans"], c:1, e:"The OS (e.g., Windows, Linux) manages hardware resources, provides a user interface, and allows applications to run."},
      {q:"Which of the following is a wireless networking standard?", o:["USB","HDMI","Wi-Fi (IEEE 802.11)","Ethernet"], c:2, e:"Wi-Fi (IEEE 802.11) is the wireless LAN standard. USB, HDMI, and Ethernet are wired standards."},
      {q:"What is a WAN?", o:["A wireless access node","A wide area network covering large geographic areas","A local network in a building","A wireless adapter"], c:1, e:"WAN = Wide Area Network. Covers large areas (cities, countries). The Internet is the world's largest WAN."},
      {q:"What does software copyright protect?", o:["The hardware the software runs on","The interface look only","The intellectual property of the software creator","Users from paying for software"], c:2, e:"Copyright protects the intellectual property (code, design, documentation) of software creators. Copying or distributing without permission is illegal."},
      {q:"What is freeware?", o:["Software that can be freely modified","Software free to use but with the author retaining copyright","Software distributed with its source code","A free trial version"], c:1, e:"Freeware is permanently free to use. The author retains copyright so you cannot modify or sell it. Different from open source."},
      {q:"Which BEST describes a computer virus?", o:["A program that speeds up the computer","A type of hardware failure","Malicious software that attaches to files and spreads when shared","A program that blocks internet access"], c:2, e:"A virus attaches to files and spreads when infected files are shared. It can damage files and the operating system."},
      {q:"What does CPU stand for?", o:["Central Processing Unit","Computer Power Unit","Central Program Utility","Core Processing Unit"], c:0, e:"CPU = Central Processing Unit — the brain of the computer that executes program instructions. Speed measured in MHz or GHz."},
      {q:"What is the purpose of a UPS (Uninterruptible Power Supply)?", o:["Speed up the computer","Provide backup power during a power cut","Protect from viruses","Connect to Wi-Fi"], c:1, e:"A UPS provides temporary battery backup during a power failure, giving you time to save work and shut down safely."},
      {q:"Which storage medium uses laser technology to read and write data?", o:["Hard Disk Drive","USB Flash Drive","RAM","CD/DVD"], c:3, e:"CDs and DVDs use laser technology. HDDs use magnetic platters; USB drives use flash memory."},
      {q:"What is ergonomics in the context of computer use?", o:["A type of software","Designing workspaces to prevent injury and promote comfort","A data storage method","Network security design"], c:1, e:"Ergonomics designs workspaces for safe, comfortable use — correct chair height, monitor distance, wrist position."},
      {q:"Which component in the CPU performs arithmetic calculations?", o:["RAM","The control unit","The ALU","The hard disk"], c:2, e:"The ALU (Arithmetic and Logic Unit) performs all mathematical calculations and logical comparisons inside the CPU."},
      {q:"What is multitasking in an operating system?", o:["Running multiple CPUs","Running several programs simultaneously","Multiple users logged in","Using multiple monitors"], c:1, e:"Multitasking allows several applications to run simultaneously. The CPU switches between tasks rapidly."},
      {q:"What is a peripheral device?", o:["The main processor","Any external device connected to the computer (keyboard, mouse, printer)","The computer power supply","RAM inside the computer"], c:1, e:"Peripheral devices are external hardware: input (keyboard, mouse), output (printer, monitor), and storage (USB drive)."},
      {q:"What does open source software mean?", o:["Software free to download","Software whose source code is publicly available and can be modified","Software with no copyright","A type of shareware"], c:1, e:"Open source software has publicly available source code. Anyone can view, modify, and redistribute it. E.g., Linux, Firefox."},
      {q:"What is teleworking?", o:["Working in a call centre","Using computers and internet to work from home instead of commuting","A type of network security","Programming for remote servers"], c:1, e:"Teleworking means using computers and internet to work from home instead of travelling to an office."},
      {q:"Which is the SMALLEST unit of data?", o:["Byte","Kilobyte","Bit","Nibble"], c:2, e:"A bit (binary digit) is the smallest unit — either 0 or 1. 8 bits = 1 byte. 1024 bytes = 1 kilobyte."},
      {q:"What is a server in a network?", o:["A very fast personal computer","A computer that provides services and resources to other computers on the network","A type of wireless router","A backup storage device"], c:1, e:"A server provides services (file storage, email, web hosting) to client computers on the network. It typically runs 24/7."},
      {q:"What is the purpose of a firewall?", o:["Speed up internet","Monitor and filter network traffic to block unauthorised access","Store backup data","Manage print queues"], c:1, e:"A firewall monitors network traffic and blocks unauthorised access using security rules."},
      {q:"Which statement correctly describes hardware and software?", o:["Hardware controls software","Software provides instructions that hardware follows to perform tasks","They are completely independent","Hardware is always more important"], c:1, e:"Software tells hardware what to do. Without software hardware is useless; without hardware software cannot run. They are interdependent."},"""

# MODULE 1 – Online Essentials (10→36, +26)
additions['e:"System \\u2192 Preferences \\u2192 Keyboard allows you to add or change keyboard layouts (e.g., adding French or Arabic input methods)."},'] = ""
# Use a simpler match
M1_LAST = 'e:"System → Preferences → Keyboard allows you to add or change keyboard layouts (e.g., adding French or Arabic input methods)."},'
additions[M1_LAST] = \
"""      {q:"Which keyboard shortcut COPIES selected content?", o:["Ctrl+X","Ctrl+V","Ctrl+C","Ctrl+A"], c:2, e:"Ctrl+C copies the selection. Ctrl+X cuts it. Ctrl+V pastes it. Ctrl+A selects all."},
      {q:"Which keyboard shortcut CUTS selected content?", o:["Ctrl+C","Ctrl+X","Ctrl+V","Ctrl+Z"], c:1, e:"Ctrl+X cuts (removes) the selection and places it on the clipboard. Ctrl+V to paste it elsewhere."},
      {q:"Which keyboard shortcut performs REDO?", o:["Ctrl+Z","Ctrl+R","Ctrl+Y","Ctrl+S"], c:2, e:"Ctrl+Y re-applies the last action that was undone with Ctrl+Z."},
      {q:"How do you change screen resolution in Ubuntu Gnome?", o:["Applications → Preferences → Display","System → Preferences → Screen Resolution","Edit → Display Settings","Control Panel → Screen"], c:1, e:"System → Preferences → Screen Resolution lets you change pixel dimensions (e.g., 1024x768 to 1280x1024)."},
      {q:"What does FORMATTING a removable disk do?", o:["Makes it faster","Backs up its contents","Erases ALL data and prepares the disk for use","Compresses the data"], c:2, e:"Formatting erases ALL data and creates a new file system. Always back up data before formatting."},
      {q:"How do you install software in Ubuntu graphically?", o:["File Manager → Software","Applications → Add/Remove or System → Synaptic Package Manager","System → Administration → Install","Applications → Office → Install"], c:1, e:"Applications → Add/Remove (or System → Synaptic Package Manager) installs and removes software in Ubuntu."},
      {q:"What does MINIMISE a window do?", o:["Makes the window smaller on screen","Closes the window","Hides the window to the taskbar while keeping it running","Moves the window to another desktop"], c:2, e:"Minimise hides the window to the taskbar. The application keeps running. Click the taskbar button to restore it."},
      {q:"What does MAXIMISE a window do?", o:["Makes the window slightly larger","Expands the window to fill the entire screen","Moves the window to the top","Closes all other windows"], c:1, e:"Maximise expands the window to fill the whole screen. Click the restore button to return to the previous size."},
      {q:"In Linux/Ubuntu, what does the single forward slash / represent?", o:["The user home directory","The current directory","The root of the entire file system","A separator only"], c:2, e:"In Linux, / is the root directory — the very top of the file system hierarchy. All other directories branch from it."},
      {q:"What is the home directory for a user named fatima in Ubuntu?", o:["/root/fatima","/home/fatima","/users/fatima","/fatima"], c:1, e:"Ubuntu home directories are /home/username. For 'fatima' it is /home/fatima — where personal files and settings are stored."},
      {q:"How do you view system information (RAM, CPU, OS version) in Ubuntu?", o:["System → About this computer","System → Administration → System Monitor","Applications → System Info","Help → About Ubuntu"], c:1, e:"System → Administration → System Monitor shows OS version, RAM installed, and CPU usage."},
      {q:"What is the right-click context menu used for?", o:["Selecting multiple files","Opening a file","Showing actions relevant to the selected object","Zooming into an item"], c:2, e:"Right-clicking shows a context menu with actions specific to that item (open, copy, rename, delete, properties)."},
      {q:"How do you CREATE a new folder in Nautilus?", o:["File → New Document","File → Create Folder","Right-click → Create Folder","Edit → New Folder"], c:2, e:"Right-click in an empty area in Nautilus → Create Folder. Or use File → Create Folder from the menu."},
      {q:"How do you RENAME a file in Nautilus?", o:["Double-click the file","Right-click → Rename","File → Rename","Ctrl+R"], c:1, e:"Right-click the file and select Rename, then type the new name and press Enter."},
      {q:"What does pressing Print Screen do?", o:["Sends the screen to the printer","Captures a screenshot of the ENTIRE screen","Captures only the active window","Opens the print dialog"], c:1, e:"Print Screen captures the entire screen to the clipboard. Alt+Print Screen captures only the active window."},
      {q:"What happens when you EMPTY the Trash?", o:["Files are moved to an archive","Files are permanently deleted and cannot be recovered","Files are compressed","Files are moved to /lost+found"], c:1, e:"Emptying the Trash permanently deletes all files in it. This action cannot be undone."},
      {q:"How do you view HIDDEN files in Nautilus?", o:["View → Show All Files","Edit → Show Hidden Files","View → Show Hidden Files","Ctrl+H"], c:2, e:"View → Show Hidden Files (or Ctrl+H) toggles display of hidden files (those starting with a dot)."},
      {q:"What is a file EXTENSION?", o:["The file size","The part after the dot (e.g., .txt, .jpg) indicating the file type","The file creation date","The folder the file is in"], c:1, e:"A file extension indicates file type and which application opens it. Changing extension does not convert the file."},
      {q:"How do you change the date and time in Ubuntu Gnome?", o:["System → Preferences → Date & Time","Right-click the clock on the panel → Adjust Date & Time","Edit → System Clock","Applications → Utilities → Calendar"], c:1, e:"Right-click the clock on the top panel → Adjust Date & Time to change the system date and time."},
      {q:"What does Ctrl+S do in most applications?", o:["Select all","Start a new document","Save the current file","Open spell check"], c:2, e:"Ctrl+S saves the current file. It is the universal Save shortcut in most applications."},
      {q:"What does Ctrl+N do in most applications?", o:["Save the file","Open a new blank document","Close the application","Open file manager"], c:1, e:"Ctrl+N creates a new blank document. It is equivalent to File → New."},
      {q:"How do you force quit a frozen application in Ubuntu?", o:["Press Ctrl+C","Open System Monitor and kill the process","Press Alt+F4","Restart the computer"], c:1, e:"System → Administration → System Monitor: find the frozen app, select it, click Kill Process."},
      {q:"What does the taskbar at the BOTTOM of the Gnome desktop show?", o:["Running applications and open windows","System settings only","The file manager","Nothing useful"], c:0, e:"The bottom panel shows currently open windows and running applications. Clicking a button minimises or restores that window."},
      {q:"What is the keyboard shortcut to close the current window?", o:["Ctrl+W","Alt+F4","Ctrl+Q","Ctrl+X"], c:1, e:"Alt+F4 closes the currently active window. Ctrl+W typically closes the current tab within an application."},
      {q:"How do you MOVE a file to a different folder in Nautilus?", o:["Copy then delete the original","Drag to the new location, or Cut (Ctrl+X) then Paste (Ctrl+V)","Right-click → Move To Folder","Files cannot be moved, only copied"], c:1, e:"To move a file: drag it to the destination folder, or Cut (Ctrl+X) then Paste (Ctrl+V) in the new folder."},
      {q:"How do you view PROPERTIES of a file (size, type, date modified)?", o:["File → Properties","Ctrl+P","Right-click → Properties","Double-click the file"], c:2, e:"Right-click any file or folder and select Properties to see its size, type, permissions, and dates."},"""

# MODULE 2 – Word Processing (10→36, +26)
M2_LAST = 'e:"Ctrl+A selects all content in the document. This is useful before applying formatting to the entire document at once."},'
additions[M2_LAST] = \
"""      {q:"Which keyboard shortcut makes selected text BOLD?", o:["Ctrl+B","Ctrl+I","Ctrl+U","Ctrl+E"], c:0, e:"Ctrl+B applies Bold. Ctrl+I = Italic. Ctrl+U = Underline. Select the text first then apply the shortcut."},
      {q:"Which keyboard shortcut makes selected text ITALIC?", o:["Ctrl+B","Ctrl+I","Ctrl+U","Ctrl+L"], c:1, e:"Ctrl+I applies Italic formatting. Select text first then press Ctrl+I. Press again to remove italic."},
      {q:"What is the keyboard shortcut to PRINT a document?", o:["Ctrl+S","Ctrl+P","Ctrl+D","F7"], c:1, e:"Ctrl+P opens the Print dialog in Writer and most other applications."},
      {q:"What is the shortcut to open a NEW document in Writer?", o:["Ctrl+O","Ctrl+N","Ctrl+W","Ctrl+S"], c:1, e:"Ctrl+N opens a new blank document. Ctrl+O opens an existing file. Ctrl+S saves the current document."},
      {q:"What is the shortcut to OPEN an existing document?", o:["Ctrl+N","Ctrl+O","Ctrl+F","Ctrl+A"], c:1, e:"Ctrl+O opens the Open File dialog to browse for and open an existing document."},
      {q:"How is font size measured?", o:["In pixels","In inches","In points (pt)","In centimetres"], c:2, e:"Font size is measured in points (pt). 12pt is standard body text. 72pt is approximately 1 inch tall."},
      {q:"What does line spacing control?", o:["Space between characters","Space between paragraphs only","Vertical space between lines of text within a paragraph","The margin size"], c:2, e:"Line spacing controls vertical distance between lines. Common options: Single (1.0), 1.5, Double (2.0)."},
      {q:"What is a Header in a word processor?", o:["The first line of a document","Text that appears at the top of every page","The document title only","The first paragraph"], c:1, e:"A Header repeats at the top of every page (document title, author name). A Footer repeats at the bottom."},
      {q:"How do you insert automatic page numbers in Writer?", o:["Type numbers manually on each page","Insert Footer then Insert → Fields → Page Number","Format → Page → Numbers","Edit → Insert → Page Number"], c:1, e:"Insert → Footer, place cursor in footer, then Insert → Fields → Page Number for automatic page numbering."},
      {q:"What is Print Preview used for?", o:["Print a test copy","See how the document looks when printed before printing","Check word count","Preview file formatting only"], c:1, e:"File → Page Preview shows exactly how the document will look when printed — page breaks, headers, footers, margins."},
      {q:"What does Collate mean when printing multiple copies?", o:["Print all copies of page 1 then all of page 2","Print one complete set (1-2-3) before starting the next copy","Print in colour","Print double-sided"], c:1, e:"Collate prints full sets: 1-2-3, 1-2-3, 1-2-3. Without collating: 1-1-1, 2-2-2, 3-3-3. Saves manual sorting."},
      {q:"What does AutoCorrect do?", o:["Checks grammar after you finish","Automatically fixes common spelling mistakes as you type","Suggests alternative words","Checks formatting consistency"], c:1, e:"AutoCorrect fixes common typing errors automatically as you type (e.g., 'teh' becomes 'the'). Via Tools → AutoCorrect."},
      {q:"How do you INSERT a table in Writer?", o:["Edit → Table","Format → Insert Table","Table → Insert Table","Insert → Table"], c:2, e:"Table → Insert Table opens a dialog where you specify rows and columns."},
      {q:"What does merging cells in a table do?", o:["Copies cells to a new location","Combines multiple cells into one larger cell","Sorts cells alphabetically","Adds a border between cells"], c:1, e:"Merging combines selected cells into one cell. E.g., merging the top row creates a wide header cell. Via Table → Merge Cells."},
      {q:"How do you insert an IMAGE into a Writer document?", o:["Edit → Paste Image","Insert → Picture → From File","Format → Image","View → Insert Picture"], c:1, e:"Insert → Picture → From File opens a browser to locate and insert an image. Resize by dragging the handles."},
      {q:"What is the difference between Subscript and Superscript?", o:["Subscript is larger; superscript is smaller","Subscript appears below the baseline (H2O); superscript above (x squared)","They are the same","Subscript is italic; superscript is bold"], c:1, e:"Subscript places text below the line (H2O for chemistry). Superscript places text above (x2 for powers). Via Format → Character."},
      {q:"What are Styles in Writer?", o:["Themes for the page background","Named formatting settings ensuring consistent formatting","Different font families","Colour schemes"], c:1, e:"Styles (Heading 1, Body Text) are named formatting rules. They ensure consistency and allow bulk updates throughout the document."},
      {q:"What is LANDSCAPE page orientation?", o:["Taller than it is wide","Wider than it is tall","A page with no margins","A two-column page"], c:1, e:"Landscape rotates the page so it is wider than tall — good for wide tables. Portrait (taller) is standard for letters."},
      {q:"How do you change page MARGINS in Writer?", o:["Edit → Page Margins","Format → Page → Page tab","Insert → Margins","View → Page Setup"], c:1, e:"Format → Page → Page tab sets margins (top, bottom, left, right), paper size, and orientation."},
      {q:"What does Find (Ctrl+F) do?", o:["Replace text throughout the document","Search for a specific word or phrase in the document","Check the word count","Find and delete all instances"], c:1, e:"Ctrl+F opens the Find toolbar to search for text. Ctrl+H opens Find AND Replace to find and swap text."},
      {q:"What does the Word Count function show?", o:["Number of pages only","Number of words, characters, paragraphs, and lines","The font size","Reading time"], c:1, e:"Tools → Word Count shows words, characters (with/without spaces), paragraphs, and lines in the document or selection."},
      {q:"Which key moves the cursor to the BEGINNING of a line?", o:["Ctrl+Home","Home","Ctrl+Left Arrow","Page Up"], c:1, e:"Home moves the cursor to the beginning of the current line. Ctrl+Home moves to the very start of the document."},
      {q:"What is a bulleted list used for?", o:["Items in a specific numerical order","An unordered list where sequence does not matter","A list that is automatically sorted","A list that calculates totals"], c:1, e:"Bulleted lists are for items where order does not matter. Numbered lists are for sequential steps."},
      {q:"How do you delete a ROW from a table in Writer?", o:["Select the row and press Delete","Select the row, right-click → Delete Rows","Table → Remove Row","Edit → Delete Row"], c:1, e:"Click in the row, right-click, select Delete Rows. This removes the entire row from the table."},
      {q:"What is RTF and why is it useful?", o:["Rich Text File — a video format","Rich Text Format — preserves basic formatting and opens in almost any word processor","A plain text format with no formatting","An OpenOffice-only format"], c:1, e:"RTF (Rich Text Format) preserves basic formatting (bold, fonts) and can be opened by virtually any word processor on any OS."},
      {q:"What does Insert → Header do in Writer?", o:["Adds a title at the top of the first page only","Adds a header area at the top of every page for repeating content","Creates a page border","Inserts a text box at the top"], c:1, e:"Insert → Header adds a header zone at the top of every page. Content placed there (title, page number, date) repeats on all pages."},"""

# MODULE 3 – Spreadsheets (10→36, +26)
M3_LAST = 'e:"AutoFilter adds dropdown arrows to column headers, allowing you to display only rows that match specific criteria without deleting any data."},'
additions[M3_LAST] = \
"""      {q:"What is a RELATIVE cell reference?", o:["A reference that never changes when copied","A reference that adjusts automatically when a formula is copied to a new cell","A reference to another worksheet","A reference locked with dollar signs"], c:1, e:"A relative reference (e.g., A1) adjusts when copied. Copying =A1+B1 one row down gives =A2+B2."},
      {q:"What is the correct formula to calculate the AVERAGE of A1:A10?", o:["=AVG(A1:A10)","=MEAN(A1:A10)","=AVERAGE(A1:A10)","=SUM(A1:A10)/10"], c:2, e:"=AVERAGE(A1:A10) calculates the arithmetic mean of the range. It is the standard function for averages in Calc."},
      {q:"Which function returns the SMALLEST value in a range?", o:["=SMALL()","=MIN()","=LEAST()","=LOW()"], c:1, e:"=MIN(range) returns the smallest value. =MAX() returns the largest."},
      {q:"What does the IF function do?", o:["Counts cells meeting a condition","Returns one value if condition is true and another if false","Searches for a value in a range","Adds cells meeting a condition"], c:1, e:"=IF(condition, value_if_true, value_if_false). E.g., =IF(A1>50,\"Pass\",\"Fail\") shows Pass if A1 is over 50, otherwise Fail."},
      {q:"What does =COUNTIF(A1:A20,\">50\") do?", o:["Adds all values greater than 50","Counts cells with a value greater than 50","Finds the maximum value above 50","Highlights cells above 50"], c:1, e:"=COUNTIF(range, criteria) counts cells meeting a condition. This counts how many cells in A1:A20 are greater than 50."},
      {q:"What does a mixed reference like $A1 mean?", o:["Both column and row are locked","Only the column A is locked; the row changes when copied","Only the row is locked","The cell cannot be edited"], c:1, e:"$A1 locks only the column (A stays fixed) but the row number changes when the formula is copied. A$1 locks only the row."},
      {q:"Which chart type is BEST for showing trends over time?", o:["Pie chart","Bar chart","Line chart","Scatter chart"], c:2, e:"Line charts show trends over time (e.g., monthly sales). Data points connected by lines show the direction of change."},
      {q:"What does the #REF! error indicate?", o:["Wrong data type","Division by zero","Invalid cell reference (e.g., a referenced row was deleted)","Unrecognised function name"], c:2, e:"#REF! appears when a formula contains an invalid reference — typically because a referenced row or column was deleted."},
      {q:"What does the #NAME? error indicate?", o:["Invalid cell reference","Worksheet name error","Unrecognised function name or text in the formula","Division by zero"], c:2, e:"#NAME? appears when Calc does not recognise text in a formula — usually a misspelled function name (e.g., =SUUM instead of =SUM)."},
      {q:"What is CONDITIONAL FORMATTING?", o:["A formula applying conditions","Formatting applied automatically based on cell values (e.g., red if negative)","A method of filtering data","Applying number formats to cells"], c:1, e:"Conditional formatting automatically changes a cell's appearance based on its value. Via Format → Conditional → Condition."},
      {q:"What is the purpose of FREEZE PANES?", o:["Lock cells so they cannot be edited","Keep column or row headers visible while scrolling through large data","Protect the worksheet from changes","Merge rows and columns"], c:1, e:"Freeze Panes (View → Freeze Rows and Columns) keeps specified rows/columns visible when scrolling — useful for always seeing headers."},
      {q:"How do you SORT data in a spreadsheet?", o:["Data → Sort — choose column and ascending or descending order","Format → Sort","Edit → Arrange Data","View → Sort Columns"], c:0, e:"Data → Sort opens a dialog to choose the column and whether the order is ascending (A-Z) or descending (Z-A)."},
      {q:"What is a CHART TITLE used for?", o:["To identify individual data series","To label the chart and describe what data it shows","To set the chart scale","To add notes below the chart"], c:1, e:"A chart title describes what the chart shows (e.g., Monthly Sales 2024). Axis labels describe what each axis represents."},
      {q:"What does formatting a cell as CURRENCY do?", o:["Converts to a different currency","Displays number with a currency symbol and two decimal places","Locks the cell from editing","Changes the cell colour"], c:1, e:"Currency formatting displays numbers with a currency symbol and two decimal places (e.g., 1250.00). The stored value does not change."},
      {q:"What does formatting a cell as PERCENTAGE do?", o:["Divides the value by 100 and adds a percent sign","Multiplies the value by 100 and adds a percent sign","Rounds to nearest percent","Locks value between 0 and 100"], c:1, e:"Percentage format multiplies the stored value by 100 and adds %. So 0.75 displays as 75%."},
      {q:"What is an ODS file?", o:["An OpenOffice Drawing file","An OpenDocument Spreadsheet — default format for Calc","A database file","An OpenOffice Presentation file"], c:1, e:".ods = OpenDocument Spreadsheet, the default format for OpenOffice Calc. Part of the open ODF standard."},
      {q:"What does COUNTA count?", o:["Only cells with numbers","All non-empty cells (numbers, text, dates, everything)","Only cells with text","Cells meeting a specific condition"], c:1, e:"=COUNTA(range) counts ALL non-empty cells regardless of data type. =COUNT(range) counts only numeric cells."},
      {q:"Which formula calculates 15% of the value in cell B2?", o:["=B2/15","=B2*0.15","=B2+15%","=15%/B2"], c:1, e:"To find a percentage: multiply by the decimal equivalent. 15% = 0.15, so =B2*0.15. Alternatively =B2*15% also works."},
      {q:"How do you add a new WORKSHEET tab?", o:["File → New Sheet","Insert → Sheet or right-click a tab → Insert Sheet","Format → Add Sheet","Edit → New Worksheet"], c:1, e:"Right-click a worksheet tab → Insert Sheet, or use Insert → Sheet from the menu."},
      {q:"What is a BAR CHART best used for?", o:["Showing trends over time","Comparing individual values across categories","Showing parts of a whole","Plotting mathematical relationships"], c:1, e:"Bar or column charts compare values across different categories (e.g., sales by region, scores per student)."},
      {q:"What is a PRINT AREA?", o:["The printer physical size limit","A defined range of cells that will print instead of the entire sheet","The margins around printed content","The header and footer area"], c:1, e:"A print area defines which cells to print. Set via Format → Print Ranges → Define. Only that range will print."},
      {q:"What does pressing F2 do in a spreadsheet cell?", o:["Starts a new formula","Opens Format Cells dialog","Enters Edit mode for the selected cell","Inserts a new row"], c:2, e:"F2 enters Edit mode for the selected cell, placing the cursor inside it for editing existing content."},
      {q:"What does the ampersand operator & do in a formula?", o:["Multiplies two values","Concatenates (joins) two text strings","Checks if values are equal","Calculates a percentage"], c:1, e:"& joins text strings. =A1&\" \"&B1 joins text from A1, a space, and B1. If A1=John and B1=Smith the result is John Smith."},
      {q:"What is the purpose of the FORMULA BAR?", o:["Showing chart data","Displaying and editing the actual content or formula of the selected cell","Showing toolbar shortcuts","Displaying cell formatting"], c:1, e:"The Formula Bar below the toolbar shows the actual content of the selected cell — the raw formula or value, not just the displayed result."},
      {q:"Which function returns TODAY's date?", o:["=DATE()","=NOW()","=TODAY()","=CURRENT()"], c:2, e:"=TODAY() returns today's date and updates each time the file opens. =NOW() returns the current date AND time."},
      {q:"What does the #DIV/0! error mean?", o:["Wrong data type","Invalid cell reference","The formula is dividing by zero or an empty cell","Unrecognised function name"], c:2, e:"#DIV/0! appears when a formula tries to divide by zero or by an empty cell. Check that the denominator is not zero."},"""

# MODULE 4 – Databases (10→36, +26)
M4_LAST = 'e:"Referential Integrity enforces rules on related tables — e.g., you cannot add a record in a child table that references a non-existent record in the parent table."},'
additions[M4_LAST] = \
"""      {q:"What is a MEMO field type used for?", o:["Storing phone numbers","Storing large amounts of text such as paragraphs and notes","Storing dates and times","Storing Yes or No values"], c:1, e:"A Memo field stores large text — paragraphs, notes, descriptions. A Text field is limited (usually 255 characters); Memo has no practical limit."},
      {q:"What is a BOOLEAN field type used for?", o:["Storing large numbers","Storing binary data files","Storing Yes/No or True/False values only","Storing short text"], c:2, e:"A Boolean field stores only two values: Yes/No, True/False, or 1/0. Used for binary attributes like Is Active or Has Paid."},
      {q:"What does the DATE field type allow that TEXT does not?", o:["Store dates in any format","Perform date arithmetic such as days between two dates","Display dates with colours","Store times as well as dates"], c:1, e:"Date fields support arithmetic — subtracting one date from another gives the number of days between them. Text fields store dates as text only."},
      {q:"What is NORMALISATION in database design?", o:["Making the database faster","Organising data to eliminate redundancy so each table covers one topic only","Encrypting sensitive data","Creating indexes for all fields"], c:1, e:"Normalisation reduces data redundancy and improves integrity. The key rule is that each table should contain data about only ONE topic."},
      {q:"What is an AUTO-NUMBER field?", o:["A field that sums values automatically","A field that automatically assigns a unique sequential number to each new record","A field that counts all records","A field storing the current date automatically"], c:1, e:"AutoNumber automatically generates a unique sequential number (1, 2, 3...) for each new record. Commonly used as the primary key."},
      {q:"What is a DEFAULT VALUE for a field?", o:["The maximum allowed value","A value automatically entered into a field when no data is provided","The primary key value","The most common value in the field"], c:1, e:"A default value is inserted automatically when a record is added and no value is entered for that field. E.g., Country defaulting to UK."},
      {q:"What is a VALIDATION RULE?", o:["A rule that backs up the database automatically","A restriction on what data can be entered into a field","A rule that sorts records automatically","A formula that calculates field values"], c:1, e:"A validation rule restricts data entry to acceptable values. E.g., Age must be between 0 and 120. Helps maintain data integrity."},
      {q:"A MANY-TO-MANY relationship requires:", o:["Two foreign keys in one table","A third junction table linking both tables","No primary keys","Both tables to be merged"], c:1, e:"Many-to-many (e.g., Students and Courses) is resolved by a junction table containing the primary keys of both tables."},
      {q:"What is a SELECT QUERY?", o:["A query that deletes records","A query that retrieves specific records based on criteria without modifying data","A query that adds records from another table","A query that modifies existing records"], c:1, e:"A Select query retrieves matching records without changing any data. It is the most common query type."},
      {q:"What does an AND condition do in a query?", o:["Returns records matching EITHER condition","Returns records matching BOTH conditions simultaneously","Returns all records","Excludes records matching both conditions"], c:1, e:"AND requires ALL conditions to be true. E.g., City=London AND Salary>30000 returns only London records with salary over 30000."},
      {q:"What does an OR condition do in a query?", o:["Returns records matching ALL conditions","Returns records matching AT LEAST ONE of the conditions","Combines two tables","Excludes all matching records"], c:1, e:"OR returns records where at least one condition is true. E.g., City=London OR City=Paris returns records from either city."},
      {q:"What does the ? wildcard represent in a query?", o:["Any number of characters","Exactly one character","A number only","An empty value"], c:1, e:"? matches exactly ONE character. E.g., Like Sm?th matches Smith or Smyth. The * wildcard matches zero or more characters."},
      {q:"What is a REPORT WIZARD used for?", o:["Creating queries automatically","Guiding you step by step to create a formatted printable report","Importing data from Excel","Backing up the database"], c:1, e:"The Report Wizard guides you through selecting a table or query, fields, grouping, sorting, and layout to produce a formatted report."},
      {q:"What does GROUPING in a report do?", o:["Rearranges records randomly","Groups records by a field value and calculates subtotals for each group","Merges duplicate records","Sorts records alphabetically"], c:1, e:"Grouping organises report data by a field (e.g., Department) and calculates subtotals for each group."},
      {q:"What appears in the PAGE HEADER of a report?", o:["Grand totals for the whole report","The report title which appears once","Column headings that repeat at the top of every page","Individual record data"], c:2, e:"The Page Header appears at the top of every page and typically contains column headings. The Report Header appears only once at the very top."},
      {q:"What does the DETAIL section of a report contain?", o:["Summary totals","Column labels","One row of data for each record","The report footer"], c:2, e:"The Detail section repeats for every record, printing one row of data per record. It is the main body of the report."},
      {q:"What is a LOOKUP field?", o:["A field that searches other databases","A field showing a dropdown list of valid values from another table or a fixed list","A field that calculates values automatically","An index on a text field"], c:1, e:"A lookup field presents a dropdown of acceptable values instead of a blank entry box, ensuring only valid values are entered."},
      {q:"What is the navigation bar at the bottom of a form used for?", o:["Navigate between form layouts","Move between records using First, Previous, Next, Last, and New buttons","Set field properties","Switch between tables"], c:1, e:"The navigation buttons move between records: First, Previous, Next, Last, and New Record. Used to browse data in the form."},
      {q:"What does FIELD SIZE property control?", o:["The width of the column on screen","The maximum number of characters that can be stored in a text field","How the field is displayed","The sort order of the field"], c:1, e:"Field Size limits the number of characters in a text field. E.g., setting PostCode to 10 characters prevents excessive storage."},
      {q:"How is a RELATIONSHIP created between two tables in Base?", o:["By giving them the same name","By linking the primary key of one table to the foreign key of another in the Relationships window","By using a query to join them","By merging the tables together"], c:1, e:"In Tools → Relationships, drag the primary key of one table to the matching foreign key field of the other table."},
      {q:"What does REQUIRED field property mean?", o:["The field must be indexed","The field must have a value and cannot be left empty (null)","The field must have a default value","The field must be the primary key"], c:1, e:"Required = Yes means the field MUST have a value. No record can be saved with that field empty."},
      {q:"What is the difference between a FORM and a TABLE view?", o:["A form stores data; a table displays it","A form provides a user-friendly interface for entering and viewing data; the table stores the actual data","They are identical","A form stores more data than a table"], c:1, e:"The TABLE stores data in rows and columns. A FORM is a designed screen that reads from and writes to the table, making data entry easier."},
      {q:"What is a valid criterion for a Date field in a query?", o:["='01/01/2024'","Between #01/01/2024# And #31/12/2024#",">01-01-2024","='Year 2024'"], c:1, e:"Date criteria use hash symbols. Between #01/01/2024# And #31/12/2024# selects all records within the year 2024."},
      {q:"What does saving a QUERY do?", o:["Saves the result records permanently in a new table","Saves the query definition so it can be run again later with fresh data","Exports results to a spreadsheet","Creates a backup of the table"], c:1, e:"Saving a query saves the DEFINITION (the instructions). Each run retrieves fresh, current data from the table."},
      {q:"What is a FORM WIZARD used for?", o:["Automatically designing database structure","Guiding you step by step to create a data entry form","Creating reports","Importing data from spreadsheets"], c:1, e:"The Form Wizard guides you through selecting a table, choosing fields, picking a layout and style to create a data entry form."},
      {q:"Why store a phone number as TEXT rather than NUMBER?", o:["Phone numbers are too long for numbers","Text fields preserve leading zeros; number fields drop them (e.g., 0800 would become 800)","Text fields are faster","Number fields cannot store phone numbers at all"], c:1, e:"Phone numbers may have leading zeros (0800...) which number fields drop. Stored as text, leading zeros are preserved. You also do not perform maths on phone numbers."},"""

# MODULE 5 – Presentation (15→36, +21)
M5_LAST = 'e:"Best practice: brief text (bullet points not paragraphs), high contrast, consistent fonts/colours, no more than 6 bullets per slide. Consistent design throughout."},'
additions[M5_LAST] = \
"""      {q:"What is the NOTES view used for?", o:["Showing all slides as thumbnails","Viewing slide text only","Adding speaker notes below each slide for the presenter","Displaying the presentation in full screen"], c:2, e:"Notes view shows each slide with a notes area below for speaker notes visible to the presenter but NOT shown on screen during the slideshow."},
      {q:"What is the OUTLINE view in Impress?", o:["Shows all slides as thumbnails","Shows text content only (titles and bullets) without design elements","Shows the slide master","Shows one slide at a time in full detail"], c:1, e:"Outline view shows only text content of all slides in a text-based outline — useful for reviewing the text flow across all slides."},
      {q:"How do you DELETE a slide?", o:["Select it and press Backspace","Right-click the slide in the panel then select Delete Slide","Edit → Remove Slide","File → Delete Slide"], c:1, e:"Right-click the slide in the left panel and select Delete Slide. Or select the slide and press the Delete key."},
      {q:"How do you DUPLICATE a slide?", o:["Copy (Ctrl+C) then Paste (Ctrl+V) the slide","Edit → Duplicate","Insert → Duplicate Slide","Right-click → Insert Slide"], c:0, e:"Select the slide, Copy (Ctrl+C), then Paste (Ctrl+V). The duplicate appears after the original."},
      {q:"Which keyboard shortcut starts the slideshow from the CURRENT slide?", o:["F5","Ctrl+F5","Shift+F5","Alt+F5"], c:2, e:"Shift+F5 starts from the currently selected slide. F5 always starts from the first slide."},
      {q:"How do you apply a DESIGN TEMPLATE in Impress?", o:["Insert → Template","View → Design","Format → Slide Design then choose a template","Edit → Apply Design"], c:2, e:"Format → Slide Design opens built-in templates. Selecting one applies a consistent background, font, and colour scheme to all slides."},
      {q:"What is the purpose of a LAYOUT in Impress?", o:["Set the background colour","Control the arrangement of content placeholder boxes on a slide","Add animations to objects","Define slide transition effects"], c:1, e:"A layout defines the arrangement of placeholder boxes (Title Slide, Title and Content, Two Content). Applied via Format → Layout."},
      {q:"How do you insert a CHART into a slide?", o:["Insert → Chart","Format → Add Chart","Edit → Insert Chart","View → Charts → Insert"], c:0, e:"Insert → Chart inserts a chart object. A wizard opens to help choose the chart type and enter data."},
      {q:"How do you insert a TEXT BOX outside a placeholder?", o:["Click anywhere and type","Insert → Text Box then draw the box on the slide","Format → Insert Text","Edit → Add Text Box"], c:1, e:"Insert → Text Box, then click and drag on the slide to draw the text box. This places text anywhere outside standard placeholders."},
      {q:"What does Apply to All Slides do for a transition?", o:["Removes all transitions","Applies the same transition effect to every slide in the presentation","Only applies to the current slide","Applies only to the first and last slides"], c:1, e:"In Slide Show → Slide Transition, clicking Apply to All Slides applies the chosen effect to every slide for consistency."},
      {q:"What is an EXIT animation effect?", o:["Makes an object appear on the slide","Makes an object change appearance while on screen","Makes an object disappear from the slide","Transitions to the next slide"], c:2, e:"Exit effects make objects disappear during the presentation (e.g., Fly Out, Fade Out). Compare Entrance (appears) and Emphasis (changes)."},
      {q:"What print option shows one slide per page at FULL size?", o:["Handouts","Notes","Outline","Slides"], c:3, e:"Selecting Slides in the print dialog prints one full-size slide per page. Handouts print multiple per page; Notes prints with speaker notes."},
      {q:"What is GREYSCALE printing?", o:["Very low quality printing","Printing using only shades of grey instead of colour to save ink","Printing without page numbers","Printing with large margins"], c:1, e:"Greyscale uses only black, white, and grey shades. It saves expensive colour ink and is used for drafts or black-and-white printers."},
      {q:"How do you RESIZE an object on a slide?", o:["Right-click then Resize","Double-click the object","Click to select then drag the handles on the corners or edges","Use Format → Size and Position only"], c:2, e:"Click the object to select it (handles appear). Drag corner handles to resize proportionally; drag side handles to stretch in one direction."},
      {q:"What does NORMAL view in Impress show?", o:["All slides as thumbnails only","Slides panel on the left, main editing area in the centre, and notes panel at the bottom","Full screen presentation","Slide text only in outline form"], c:1, e:"Normal view is the main editing view: slides panel left, editing area centre, and speaker notes panel at the bottom."},
      {q:"What is the purpose of the SLIDE PANEL on the left?", o:["Show speaker notes","Provide a thumbnail overview for quick navigation and rearranging slides","Edit the slide master","Show the outline text"], c:1, e:"The Slides panel shows thumbnails of all slides allowing quick navigation (click to jump) and rearranging by dragging."},
      {q:"What is the file extension for an Impress TEMPLATE?", o:[".odp",".otp",".odt",".ppt"], c:1, e:".otp is the OpenDocument Presentation Template format. Templates provide layout and design but no content — open one to start a new presentation."},
      {q:"How do you MOVE an object on a slide?", o:["Right-click then Move","Click to select then drag it to the new position","Insert → Move Object","Double-click and drag"], c:1, e:"Click the object to select it, then hold the mouse button and drag it to the desired position on the slide."},
      {q:"What happens if you press ESCAPE during a slideshow?", o:["The presentation saves and closes","The slideshow exits and returns to the editing view","The current slide is deleted","The screen goes black permanently"], c:1, e:"Pressing Escape exits the slideshow and returns to the normal editing view in Impress."},
      {q:"How do you change the ORDER of items in an animation sequence?", o:["Drag animations up or down in the Animation panel","Right-click then Reorder","Format → Animation Order","Edit → Move Animation"], c:0, e:"In the Animation panel (Slide Show → Animation), drag effects up or down to change the sequence in which they play."},
      {q:"What is the purpose of speaker NOTES in Impress?", o:["They are shown on screen for the audience","They are private reminders for the presenter not visible to the audience during the show","They replace the slide content","They are printed by default with every presentation"], c:1, e:"Speaker notes are private reminders for the presenter written below each slide. They do NOT appear during the slideshow."},"""

# MODULE 6 – Online Collaboration (15→36, +21)
M6_LAST = 'e:"VPN (Virtual Private Network) creates an encrypted private communication channel over the public internet. Used by companies to let remote workers securely access internal systems."},'
additions[M6_LAST] = \
"""      {q:"What is FTP used for?", o:["Sending emails","Transferring files to and from servers over the internet","Securing web pages with encryption","Browsing web pages"], c:1, e:"FTP (File Transfer Protocol) is used for uploading and downloading files between computers over the internet."},
      {q:"Which domain extension indicates an EDUCATIONAL institution?", o:[".org",".edu",".gov",".com"], c:1, e:".edu is used by educational institutions. .org is for non-profits. .gov is for government bodies. .com is for commercial organisations."},
      {q:"What is the CC field in an email?", o:["A secret copy without others knowing","Carbon Copy — a visible copy sent to additional recipients","An encrypted copy","A confirmation code"], c:1, e:"CC (Carbon Copy) sends a copy to additional recipients. All recipients can see who is CC'd. Use BCC to hide recipients from each other."},
      {q:"What happens when you click REPLY ALL to an email?", o:["Replies only to the original sender","Replies to the original sender AND all CC recipients","Sends to all contacts in your address book","Forwards the email to all contacts"], c:1, e:"Reply All sends your reply to the original sender AND all CC recipients. Use with care — only when all recipients need your response."},
      {q:"What is SPAM email?", o:["Encrypted email","Unsolicited bulk email such as advertisements, scams, or phishing","Emails with large attachments","Emails requiring a password to open"], c:1, e:"Spam is unsolicited bulk email — advertisements, scams, or phishing attempts. Email clients filter spam into a Junk folder."},
      {q:"What is an EMAIL SIGNATURE?", o:["A digital security certificate","A block of text automatically added to the end of sent emails with name, title, and contact info","A password for email access","A type of email encryption"], c:1, e:"An email signature (name, job title, phone, website) is automatically appended to sent emails. Set up in email client Settings → Signatures."},
      {q:"What is the key difference between IMAP and POP3?", o:["POP3 syncs across devices; IMAP downloads to one device only","IMAP keeps emails on the server and syncs across all devices; POP3 downloads to one device","They are exactly the same thing","POP3 is for sending email; IMAP is for receiving"], c:1, e:"IMAP stores emails on the server and syncs across all your devices. POP3 downloads to one device and removes from server."},
      {q:"What does HTTPS mean in a web address?", o:["The page uses HTML version 5","The connection is encrypted and secure using SSL or TLS","The page is hosted on a high-traffic server","The site requires a login to access"], c:1, e:"HTTPS (HyperText Transfer Protocol Secure) encrypts communication between browser and server. Always use HTTPS for sensitive transactions."},
      {q:"What does the padlock icon in the browser address bar indicate?", o:["The website has been bookmarked","The site uses HTTPS — the connection is encrypted and secure","The site requires a password","A file is currently downloading"], c:1, e:"The padlock confirms HTTPS encryption is active. Always verify the padlock and correct domain before entering passwords or payment details."},
      {q:"How do you search for information on the internet?", o:["Type the URL directly into the address bar","Use a search engine such as Google or Bing and enter keywords","Use FTP to browse servers","Use the Bookmarks menu"], c:1, e:"Search engines (Google, Bing) index billions of web pages and return ranked results for your keywords. A search engine is different from a browser."},
      {q:"What is TABBED BROWSING?", o:["Browsing in private mode","Opening multiple web pages in separate tabs within one browser window","Using bookmarks to navigate between sites","Browsing in full-screen mode"], c:1, e:"Tabbed browsing opens multiple pages in tabs within one window. Ctrl+T opens a new tab; Ctrl+W closes the current tab."},
      {q:"What is a DIGITAL CERTIFICATE on a website?", o:["The website privacy policy document","An electronic document that verifies the website identity and enables HTTPS encryption","A cookie that identifies the user","A user login certificate"], c:1, e:"A digital certificate issued by a Certificate Authority verifies a website's identity and enables HTTPS encryption. Check it by clicking the padlock icon."},
      {q:"What is a SEARCH ENGINE?", o:["A type of web browser","A program that indexes web pages and returns results based on keywords entered","The internet itself","A protocol for browsing the web"], c:1, e:"A search engine (Google, Bing) automatically crawls and indexes web pages then ranks them by relevance to your query. It is not the same as a browser."},
      {q:"What does clearing the BROWSER CACHE do?", o:["Deletes all your bookmarks","Removes stored web page copies, freeing space and forcing the browser to download fresh versions","Logs you out of all websites","Clears your download history only"], c:1, e:"The cache stores copies of web pages for faster loading. Clearing it frees storage and forces fresh downloads — useful when pages look outdated."},
      {q:"What is NETIQUETTE?", o:["An internet security protocol","Accepted standards of polite and respectful behaviour when communicating online","A network configuration tool","A type of digital certificate"], c:1, e:"Netiquette is the convention for polite online communication: avoid ALL CAPS (considered shouting), be respectful, do not spam others."},
      {q:"What is CLOUD STORAGE?", o:["Storing data on physical USB drives","Storing data on remote servers accessed over the internet from any device","A type of computer hard drive","A wireless storage device inside your computer"], c:1, e:"Cloud storage (e.g., Google Drive, Dropbox) stores data on remote servers. Accessible from any device. Risk: requires internet and trust in the provider."},
      {q:"What does the REFRESH button (F5) do in a browser?", o:["Opens a new tab","Takes you to the home page","Reloads the current web page downloading the latest version","Goes back to the previous page"], c:2, e:"F5 or the Refresh button reloads the current page from the server. Ctrl+Shift+R does a hard refresh clearing the cached version."},
      {q:"What is the purpose of BOOKMARKS in a browser?", o:["Store downloaded files","Save website addresses for quick return access without retyping the URL","Remember passwords for websites","Block unwanted websites"], c:1, e:"Bookmarks save URLs for quick return. In Firefox: Ctrl+D to bookmark the current page; Ctrl+B to open the bookmarks sidebar."},
      {q:"What risks come with using PUBLIC Wi-Fi hotspots?", o:["Your computer runs slower than usual","Anyone on the same network may be able to intercept your unencrypted data","Your battery drains faster","The internet is just slightly slower"], c:1, e:"Public Wi-Fi is often unencrypted. Attackers can intercept traffic or set up rogue hotspots. Avoid banking or shopping on public Wi-Fi; use a VPN."},
      {q:"What is a HYPERLINK?", o:["A type of secure website","Clickable text or image that navigates to another web page or resource","An internet security protocol","A browser bookmark"], c:1, e:"A hyperlink is clickable text or an image that takes you to another page or resource. Hyperlinked text is typically blue and underlined."},
      {q:"What does the BACK button do in a browser?", o:["Reloads the current page","Takes you to the home page","Navigates to the previously visited page in browser history","Closes the current tab"], c:2, e:"The Back button (Alt+Left Arrow) navigates to the previously visited page. The Forward button (Alt+Right Arrow) goes forward again."},"""

# MODULE 7 – IT Security (12→36, +24)
M7_LAST = 'e:"Pharming manipulates DNS records so a legitimate website address takes the user to a fake (but identical) site. It is detected by checking the digital certificate (padlock icon in the browser)."},'
additions[M7_LAST] = \
"""      {q:"What is SPYWARE?", o:["Software that blocks pop-up ads","Malware that silently records and transmits user activity to an attacker","Software that encrypts files for ransom","A type of firewall"], c:1, e:"Spyware secretly monitors user activity — browsing history, keystrokes, screenshots — and sends data to an attacker without the user's knowledge."},
      {q:"What is ADWARE?", o:["Software that encrypts advertisements","Malware that displays unwanted advertisements such as pop-ups without user consent","A type of antivirus software","Software for managing email"], c:1, e:"Adware displays unwanted advertisements (pop-ups, banners). It slows performance and is often bundled with free software downloads."},
      {q:"What is a TROJAN HORSE?", o:["A virus that spreads over networks automatically","Software that appears legitimate but hides malicious code inside","Software that encrypts files and demands ransom","A program that records every keystroke"], c:1, e:"A Trojan disguises itself as legitimate software but contains hidden malicious code. Unlike viruses, it does NOT replicate itself."},
      {q:"What is a ROOTKIT?", o:["A type of firewall software","Malware that embeds in the OS, hides itself, and gives the attacker administrator-level access","Software that automatically updates the OS","A type of encryption software"], c:1, e:"A Rootkit hides deep in the operating system, conceals its presence, and grants an attacker persistent hidden admin-level access to the device."},
      {q:"What is a KEYLOGGER?", o:["A device for testing keyboard input","Malware that records every keystroke and sends them to an attacker capturing passwords","A program that locks the keyboard","Software that manages login credentials securely"], c:1, e:"A Keylogger records everything typed on the keyboard — passwords, messages, banking details — and secretly transmits this data to an attacker."},
      {q:"What is a BACKDOOR?", o:["A physical entry point to a server room","A hidden access point in software that bypasses normal authentication controls","A type of social engineering technique","An encryption bypass tool"], c:1, e:"A Backdoor is a hidden mechanism (planted by malware or left by developers) allowing an attacker to access the system while bypassing normal security."},
      {q:"What is a BLACK HAT hacker?", o:["A security researcher hired to test systems","A hacker who attacks systems illegally for personal gain or to cause damage","A hacker who finds but never exploits vulnerabilities","A government cybersecurity official"], c:1, e:"A Black Hat hacker (also called a Cracker) gains unauthorised access to systems illegally — for financial gain, data theft, or causing damage."},
      {q:"What is a GREY HAT hacker?", o:["A government-approved hacker","One who finds vulnerabilities without prior consent but without malicious intent","An employed security penetration tester","An anonymous hacker with no specific goals"], c:1, e:"A Grey Hat accesses systems without permission (like Black Hat) but without malicious intent (like White Hat) — typically to find and report vulnerabilities."},
      {q:"What is SHOULDER SURFING?", o:["Hacking via wireless networks","Physically watching someone type their credentials or PIN","Copying someone's browser bookmarks remotely","A method of intercepting network packets"], c:1, e:"Shoulder surfing is a social engineering attack where an attacker physically observes as you type your password, PIN, or other sensitive data."},
      {q:"What is PRETEXTING?", o:["Creating fake phishing websites","Creating a false scenario such as pretending to be IT support to extract information from someone","Sending fake antivirus alerts","Posting false information on social media"], c:1, e:"Pretexting fabricates a scenario to manipulate someone. E.g., calling while pretending to be IT support and asking for a password to fix an urgent issue."},
      {q:"What is INFORMATION DIVING (Dumpster Diving)?", o:["Searching deep web databases for stolen data","Searching through discarded papers and rubbish bins for useful information like passwords","Hacking into cloud storage systems","Extracting data from encrypted hard drives"], c:1, e:"Information Diving involves searching rubbish bins or discarded documents for sensitive data — notes with passwords, printed reports. Shredding documents prevents this."},
      {q:"What is SKIMMING in the context of identity theft?", o:["Reading someone's browser history","Cloning payment card data using a hidden device fitted to ATMs or card readers","Taking photos of credit cards in public","Guessing PIN numbers by trial and error"], c:1, e:"Skimming uses a hidden device to read and clone data from a payment card's magnetic stripe at an ATM or point-of-sale terminal."},
      {q:"What makes a STRONG password?", o:["At least 4 characters, easy to remember, same for all accounts","At least 8 characters with a mix of uppercase, lowercase, numbers, and special characters","Only numbers for easy typing","Your name and birth year combined"], c:1, e:"A strong password is 8+ characters (14+ very strong), mixing uppercase, lowercase, numbers, and special characters. Never use names or dates. Use a unique password per account."},
      {q:"What is a PASSWORD MANAGER?", o:["A person who manages computer access","Software that stores all passwords encrypted and protected by one master password","A browser feature that only remembers website passwords","An antivirus feature for passwords"], c:1, e:"A password manager stores all passwords encrypted, protected by a single master password. Risk: if the master password is compromised, all passwords are exposed."},
      {q:"What is WEP and why is it no longer recommended?", o:["Wireless Encryption Protocol — still the strongest standard","Wired Equivalent Privacy (1999) — the first wireless encryption, now considered broken due to its short key length","A type of wireless firewall system","A wireless network monitoring protocol"], c:1, e:"WEP (1999) was the first wireless encryption standard but its short key can be cracked in minutes. It was replaced by WPA (2003) and WPA2 (2004)."},
      {q:"What is ENCRYPTION?", o:["Compressing files to save storage space","Scrambling data using an algorithm and key so only authorised parties with the correct key can read it","Backing up data to a secure remote location","A method of detecting viruses in files"], c:1, e:"Encryption transforms readable data (plaintext) into unreadable data (ciphertext) using an algorithm and key. Used in HTTPS, VPN, and disk encryption."},
      {q:"Under GDPR, what does TRANSPARENCY mean?", o:["All personal data must be publicly accessible","Users have the right to know how their personal data is collected and used","Data must be stored in transparent database containers","Companies must publish their source code"], c:1, e:"Transparency means organisations must inform users about what personal data is collected, why, how it is used, and who it is shared with."},
      {q:"Under GDPR, what does PROPORTIONALITY mean?", o:["Security measures must match the company market size","Security measures must be proportional to the actual level of risk","All data must be protected to the same level regardless of sensitivity","Personal data cannot be stored for more than one year"], c:1, e:"Proportionality means security measures must be appropriate to the risk level. Sensitive data (medical, financial) requires stronger protection than less sensitive data."},
      {q:"Who is the DATA CONTROLLER under GDPR?", o:["The person whose data is being processed","A government body overseeing data protection","The organisation or person who determines the purpose and means of processing personal data","The IT manager who manages the database"], c:2, e:"The Data Controller determines WHY and HOW personal data is processed and is legally responsible for ensuring GDPR compliance."},
      {q:"What rights does a DATA SUBJECT have under GDPR?", o:["No rights — collected data belongs to the organisation","Right to be informed, to access their data, to correct it, and to object to processing","Only the right to access their own data","Rights only available to citizens of EU member states"], c:1, e:"Under GDPR data subjects have: right to be informed, right of access, right to rectification, right to object, and in some cases the right to erasure (right to be forgotten)."},
      {q:"What is COMPUTER CRIME?", o:["Using a computer for more than 8 hours per day","Illegal activities involving computers — unauthorised access, fraud, cyberbullying, identity theft","Downloading legal free software","Using a computer without a valid software licence"], c:1, e:"Computer crime includes hacking, fraud, identity theft, cyberbullying, and online fraud. These activities are prosecutable by law in most countries."},
      {q:"What does a NETWORK ADMINISTRATOR do?", o:["Only installs new computer hardware","Manages network security, user accounts, access rights, software updates, and monitors network activity","Only repairs hardware faults","Only manages the company public website"], c:1, e:"A Network Administrator manages the entire network: user accounts, security policies, access rights, software updates, traffic monitoring, and security incident response."},
      {q:"What is a BACKUP and why is it important?", o:["A duplicate copy of a running application","Regularly created copies of data to recover from loss, corruption, hardware failure, or ransomware attack","An encrypted version of the hard disk","A password-protected folder for sensitive files"], c:1, e:"Regular backups create copies on separate media (external drive, cloud). If original data is lost or encrypted by ransomware, it can be restored from the backup."},
      {q:"What is EAVESDROPPING on a wireless network?", o:["Physically listening to nearby conversations","Intercepting and reading data transmitted over an unencrypted wireless network","Reading someone else email without permission","A type of phishing attack via Wi-Fi"], c:1, e:"Wireless eavesdropping intercepts data sent over unencrypted Wi-Fi. It is prevented by using HTTPS and WPA2 wireless encryption."},"""

# ── APPLY ADDITIONS ────────────────────────────────────────────────────────────
count = 0
for marker, new_qs in additions.items():
    if not marker or not new_qs:
        continue
    idx = content.find(marker)
    if idx == -1:
        print(f"NOT FOUND: {marker[:70]}")
        continue
    insert_at = idx + len(marker)
    content = content[:insert_at] + '\n' + new_qs + content[insert_at:]
    count += 1
    print(f"OK mod {count}: inserted after '{marker[:60]}'")

print(f"\nModules updated: {count}/8")

# ── UPDATE showQuizScore PASS LOGIC ───────────────────────────────────────────
OLD_GRADE = "  const grade   = pct >= 80 ? '🏆 Excellent!' : pct >= 60 ? '👍 Good Pass' : pct >= 40 ? '📚 Keep Studying' : '🔄 Try Again';"
NEW_GRADE = "  const passed  = pct >= 75;\n  const grade   = pct >= 90 ? '🏆 Excellent!' : pct >= 75 ? '✅ PASS' : pct >= 50 ? '📚 Keep Studying' : '🔄 Try Again';"

OLD_HTML = """  display.innerHTML = `
    <div class="score-display">
      <div class="big-score">${pct}%</div>
      <div class="score-label">${grade}</div>
      <div class="score-breakdown">
        <div class="score-item"><div class="val correct">${correct}</div><div class="lbl">Correct</div></div>
        <div class="score-item"><div class="val wrong">${qs.length-correct}</div><div class="lbl">Wrong</div></div>
        <div class="score-item"><div class="val">${qs.length}</div><div class="lbl">Total</div></div>
      </div>
    </div>
  `;"""

NEW_HTML = """  display.innerHTML = `
    <div class="score-display">
      <div class="big-score" style="color:${passed ? 'var(--success)' : 'var(--danger)'}">${pct}%</div>
      <div class="score-label">${grade}</div>
      <div style="font-size:0.85rem;margin:6px 0 10px;color:${passed ? 'var(--success)' : 'var(--danger)'}">
        ${passed ? '✅ PASS — above the 75% pass mark' : '❌ FAIL — pass mark is 75% (27/36 correct)'}
      </div>
      <div class="score-breakdown">
        <div class="score-item"><div class="val correct">${correct}</div><div class="lbl">Correct</div></div>
        <div class="score-item"><div class="val wrong">${qs.length-correct}</div><div class="lbl">Wrong</div></div>
        <div class="score-item"><div class="val">${qs.length}</div><div class="lbl">Total</div></div>
      </div>
    </div>
  `;"""

if OLD_GRADE in content:
    content = content.replace(OLD_GRADE, NEW_GRADE)
    print("OK: grade logic updated")
else:
    print("WARN: grade logic not found")

if OLD_HTML in content:
    content = content.replace(OLD_HTML, NEW_HTML)
    print("OK: score display updated")
else:
    print("WARN: score display not found")

# ── WRITE FILES ───────────────────────────────────────────────────────────────
with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print("\nWrote icdl_study_app.html")

shutil.copy(path, "C:/Users/Windows 10/Desktop/r ta/index.html")
print("Copied to index.html")

# ── VERIFY ────────────────────────────────────────────────────────────────────
with open(path, encoding='utf-8') as f:
    final = f.read()

modules = re.findall(r'id:\s*(\d+).*?quiz:\s*\[(.*?)\]\s*\}', final, re.DOTALL)
print("\nFinal question counts:")
for mod_id, quiz in modules:
    c = len(re.findall(r'\{q:', quiz))
    status = "✅" if c == 36 else f"⚠️  ({c})"
    print(f"  Module id={mod_id}: {c} questions {status}")
